

services:

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami
      - ${AIRFLOW_PROJ_DIR:-.}/include:/opt/airflow/include
      - ${AIRFLOW_PROJ_DIR:-.}/apps:/opt/spark-apps
      - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/spark-data

    networks:
      - airflow


  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      #- ${AIRFLOW_PROJ_DIR:-.}/include:/usr/local/airflow/include
      - spark-data:/bitnami
      - ${AIRFLOW_PROJ_DIR:-.}/include:/opt/airflow/include
      - ${AIRFLOW_PROJ_DIR:-.}/apps:/opt/spark-apps
      - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/spark-data
    
    networks:
      - airflow
    
    depends_on:
      - spark-master



volumes:
  spark-data: